### ISSUE TITLE
Can u add this patch ( Guild Emblem on BG maps )

### ISSUE THREAD

**Issue by xtreamprince** [secretdataz/NEMO#1]
https://github.com/MStr3am/NEMO/issues/86

and also this patch has alignment problem, if possible please fix it.  Thanks.

**Comment by vBrenth** [comment]
Did the alignment fix already?

**Comment by xtreamprince** [comment]
no the alignment not fix and it also affect on GvG map,
@secretdataz can u able to fix it? or any other way to show guild emblem on Battleground maps using new client?
