### ISSUE TITLE
[Request] Fix the Enable Who Command for 2017-06-21 & newer clients

### ISSUE THREAD

**Issue by Mikegyver** [secretdataz/NEMO#3]
as this is recommended patch on nemo, i think it is good to have this patch option being fix for 2017-06-21 & newer clients.

![enable who command](https://user-images.githubusercontent.com/16514357/29496485-47f92812-8606-11e7-83dd-0657af77084e.png)

**Comment by secretdataz** [comment]
Fixed in b554ee5
