### ISSUE TITLE
[Request] Add langtype 1 patch on sclientinfo.xml (2017-06-28 RE & newer clients)

### ISSUE THREAD

**Issue by Mikegyver** [secretdataz/NEMO#8]
since gravity introduce option to disable doram race in client's char menu creation, gravity also change these clients with no longer read clientinfo.xml. instead these clients now are reading sclientinfo.xml

however, when langtype is set to non 0, it will causing this error on launching the client.

![gettablevalue](https://user-images.githubusercontent.com/16514357/30240797-b42c7270-95a9-11e7-8c3a-006ede9a5e57.png)

perhaps a patch can be introduce to eliminate this error if the langtype is set to non 0 in scientinfo.xml

**Comment by Daegaladh** [comment]
No, Ragexe (the main server ones) reads from clientinfo.xml, while RagexeRE (sakray testing server) reads from sclientinfo.xml
In the same way Ragexe reads from ExternalSettings_kr.lub, while RagexeRE use ExternalSettings_kr_sak.lub
You also need to set in your sclientinfo:
	<servicetype>korea</servicetype>
	<servertype>sakray</servertype>

**Comment by Mikegyver** [comment]
@Daegaladh u caught me again on typo. xD. i have edit the issue title. it is on 2017-06-28 RE & newer clients.

yeap. i did like u mention

<servicetype>korea</servicetype>
<servertype>sakray</servertype>

but, this error only happen when on <langtype>1</langtype>

**Comment by Daegaladh** [comment]
That's weird, 2017-06-14bRagexeRE worked fine for me :/

**Comment by Mikegyver** [comment]
it happen starting on 2017-06-28 RE clients.
tested with 2017-06-28, 2017-07-05, 2017-08-01, 2017-09-06 RE clients.
might has something to do with gravity introduce option to disable doram race in client's char menu creation. they must have changing something on these clients start on 2017-06-28 RE clients.

**Comment by Daegaladh** [comment]
I don't have any of those, could you upload them somewhere for me to test? Thanks.

**Comment by Mikegyver** [comment]
@Daegaladh do u have discord?

**Comment by Mikegyver** [comment]
this issue has been solved. it has nothing to do with hexing / diffting.

as according to @ai4rei it is related to lua file.

and the missing lua file can be found on here

https://github.com/zackdreaver/ROenglishRE/pull/25

this should works on langtype 1 (for usa). all thanks to @Rytech2 for the lua file.
